# Generated by Django 4.0.4 on 2022-05-14 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='URL товара')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Время публикации')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='VacancyConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, verbose_name='Условие')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.CreateModel(
            name='VacancyRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, verbose_name='Требование')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('description', models.TextField(db_index=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='URL вакансии')),
                ('conditions', models.ManyToManyField(to='gastronom.vacancyconditions', verbose_name='Условия')),
                ('requirements', models.ManyToManyField(to='gastronom.vacancyrequirements', verbose_name='Требования')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('image', models.ImageField(upload_to='gastronom', verbose_name='Изображение')),
                ('slug', models.SlugField(unique=True, verbose_name='URL товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastronom.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
