# Generated by Django 4.0.4 on 2022-05-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='URL товара')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('image', models.ImageField(upload_to='gastronom', verbose_name='Изображение')),
                ('slug', models.SlugField(unique=True, verbose_name='URL товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastronom.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
