# Generated by Django 4.0.4 on 2022-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('description', models.TextField(db_index=True, verbose_name='Описание')),
                ('conditions', models.TextField(db_index=True, verbose_name='Условия')),
                ('requirements', models.TextField(db_index=True, verbose_name='Условия')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
