# Generated by Django 4.0.4 on 2022-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Название'),
        ),
    ]
