# Generated by Django 4.0.4 on 2022-05-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronom', '0002_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='slug',
            field=models.SlugField(default=None, unique=True, verbose_name='URL вакансии'),
            preserve_default=False,
        ),
    ]
