# Generated by Django 4.0.4 on 2022-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronom', '0005_alter_contact_options_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default=None, unique=True, verbose_name='URL вакансии'),
            preserve_default=False,
        ),
    ]
